// Auto-generated + curated from catelog1.xlsx — re-run scripts/import-catalog.ts to refresh images
import type { Product } from './types';

export const IMPORTED_PRODUCTS: Product[] = [
  {
    id: 6,
    name: 'Yesido Universal Adapter MC32',
    category: 'chargers',
    price: 2000,
    rating: 4.5,
    reviews: 38,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'Multi-national travel adapter supporting up to 1380W — works across 150+ countries.',
    tone: ['#FDEA0A', '#222'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'MC32'],
      ['Max Power', '1380W'],
      ['Type', 'Universal travel adapter'],
      ['Plug Compatibility', 'Multi-national standard plugs'],
    ],
    image: '/products/6.jpg',
  },
  {
    id: 7,
    name: 'Yesido Adapter Plug Kit MC25',
    category: 'chargers',
    price: 1600,
    rating: 4.4,
    reviews: 29,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'Compact 750W travel plug kit with storage case — covers all major international outlet types.',
    tone: ['#FDEA0A', '#2c2c2c'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'MC25'],
      ['Max Power', '750W'],
      ['Type', 'Travel plug kit'],
      ['Includes', 'Storage case'],
      ['Coverage', 'Multi-region plug types'],
    ],
    // No image — sunsky-online.com blocked scraping. Drop a photo at /public/products/7.jpg to show here.
  },
  {
    id: 8,
    name: 'Yesido Car Charger Y38',
    category: 'chargers',
    price: 1550,
    rating: 4.6,
    reviews: 55,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'Multi-protocol 18W fast car charger — supports QC2.0, QC3.0, FCP, and AFC.',
    tone: ['#101010', '#FDEA0A'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'Y38'],
      ['Max Output', '18W fast charging'],
      ['Protocols', 'QC2.0 · QC3.0 · FCP · AFC'],
      ['Ports', '1× USB-A'],
      ['Type', 'Car charger'],
    ],
    image: '/products/8.jpg',
  },
  {
    id: 9,
    name: 'Xiaomi Power Bank 10000mAh',
    category: 'powerbanks',
    price: 7500,
    rating: 4.7,
    reviews: 84,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'Xiaomi 10000mAh power bank with 22.5W fast charging and a built-in Type-C cable.',
    tone: ['#FDEA0A', '#1d1d1d'],
    specs: [
      ['Brand', 'Xiaomi'],
      ['Model', 'P15ZM'],
      ['Capacity', '10,000mAh'],
      ['Fast Charging', '22.5W'],
      ['Output Ports', '3 ports'],
      ['Built-in Cable', 'Type-C (two-way)'],
    ],
    // No image — mi.com blocks crawlers. Drop a photo at /public/products/9.jpg to show here.
  },
  {
    id: 10,
    name: 'Yesido Magnet Holder C160',
    category: 'holders',
    price: 2550,
    rating: 4.5,
    reviews: 47,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: '360° rotatable magnetic car holder with 4 strong magnets — dash or vent mount.',
    tone: ['#FDEA0A', '#262626'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C160'],
      ['Magnets', '4 strong magnets'],
      ['Rotation', '360°'],
      ['Adjustment', 'Flexible'],
      ['Mount', 'Dashboard / air vent'],
    ],
    image: '/products/10.webp',
  },
  {
    id: 11,
    name: 'Yesido Magnet Holder C158',
    category: 'holders',
    price: 3550,
    rating: 4.6,
    reviews: 62,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Long-arm magnetic car holder with 20 magnets — air vent clip, 360° rotation, private mould design.',
    tone: ['#FDEA0A', '#2e2e2e'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C158'],
      ['Mount', 'Air vent clip'],
      ['Arm', 'Long arm'],
      ['Magnets', '20 magnets'],
      ['Rotation', '360°'],
      ['Design', 'Private mould'],
    ],
    image: '/products/11.jpg',
  },
  {
    id: 12,
    name: 'Yesido Magnet Holder C177',
    category: 'holders',
    price: 3200,
    rating: 4.5,
    reviews: 41,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Magnetic card-style phone holder with 20 strong magnets and 360° rotating base.',
    tone: ['#FDEA0A', '#363636'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C177'],
      ['Magnets', '20 strong magnets'],
      ['Rotation', '360°'],
      ['Tilt', 'Up/down 90°'],
      ['Mount', 'Dashboard base'],
    ],
    image: '/products/12.jpg',
  },
  {
    id: 13,
    name: 'Yesido Car Holder C171',
    category: 'holders',
    price: 2700,
    rating: 4.4,
    reviews: 36,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Long-arm dashboard car holder with pressing clip and 360° rotating base.',
    tone: ['#FDEA0A', '#2a2a2a'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C171'],
      ['Mount', 'Dashboard clip'],
      ['Arm', 'Long arm'],
      ['Grip', 'Pressing clip'],
      ['Rotation', '360°'],
    ],
    image: '/products/13.jpg',
  },
  {
    id: 14,
    name: 'Yesido Magnet Holder C151',
    category: 'holders',
    price: 1200,
    rating: 4.3,
    reviews: 53,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Slim aluminium-alloy dashboard magnetic holder — washable adhesive, 6 strong magnets.',
    tone: ['#FDEA0A', '#3a3a3a'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C151'],
      ['Material', 'Aluminium alloy'],
      ['Mount', 'Adhesive dashboard'],
      ['Magnets', '6 strong magnets'],
      ['Adhesive', 'Washable glue (reusable)'],
    ],
    image: '/products/14.jpg',
  },
  {
    id: 15,
    name: 'Yesido Rear Bracket C117',
    category: 'holders',
    price: 3200,
    rating: 4.5,
    reviews: 44,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Car seat rear bracket with folding clamp arm — fits phones and tablets, 360° rotation.',
    tone: ['#101010', '#FDEA0A'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C117'],
      ['Mount', 'Car seat headrest'],
      ['Arm', 'Folding metal clamp'],
      ['Rotation', '360°'],
      ['Fits', 'Phones & tablets'],
    ],
    image: '/products/15.jpg',
  },
  {
    id: 16,
    name: 'Yesido Bicycle Bracket C94',
    category: 'holders',
    price: 4950,
    rating: 4.4,
    reviews: 31,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'ABS + silicone bicycle phone mount with adjustable fulcrum and 360° rotation.',
    tone: ['#FDEA0A', '#2e2e2e'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'C94'],
      ['Material', 'ABS + silicone'],
      ['Mount', 'Bike handlebar'],
      ['Rotation', '360°'],
      ['Fulcrum', 'Adjustable'],
    ],
    image: '/products/16.jpg',
  },
  {
    id: 17,
    name: 'Yesido Selfie Stick SF11',
    category: 'holders',
    price: 3500,
    rating: 4.5,
    reviews: 39,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: '5-part telescopic aluminium selfie stick tripod — 70cm max, Bluetooth remote, 120mAh battery.',
    tone: ['#FDEA0A', '#333'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'SF11'],
      ['Material', 'Aluminium alloy + ABS'],
      ['Max Height', '70cm'],
      ['Battery', '120mAh'],
      ['Remote', 'Bluetooth included'],
      ['Sections', '5-part telescopic'],
    ],
    image: '/products/17.jpg',
  },
  {
    id: 18,
    name: 'Yesido Selfie Stick SF14',
    category: 'holders',
    price: 10200,
    rating: 4.7,
    reviews: 28,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'Foldable Bluetooth gimbal selfie stick tripod — built-in stabilizer, 450mAh battery.',
    tone: ['#101010', '#FDEA0A'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'SF14'],
      ['Type', 'Gimbal stabilizer + tripod'],
      ['Folded Length', '19cm'],
      ['Battery', '450mAh'],
      ['Charging', 'Micro-USB'],
      ['Remote', 'Bluetooth'],
    ],
    image: '/products/18.jpg',
  },
  {
    id: 19,
    name: 'Yesido Selfie Stick SF12 Ring Light',
    category: 'holders',
    price: 7900,
    rating: 4.6,
    reviews: 52,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Aluminium selfie stick with 5-level LED ring light — 80cm max height, Bluetooth remote.',
    tone: ['#FDEA0A', '#222'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'SF12'],
      ['Feature', 'LED ring light'],
      ['Light Levels', '5 brightness levels'],
      ['Max Height', '80cm'],
      ['Battery', '120mAh'],
      ['Remote', 'Bluetooth included'],
    ],
    image: '/products/19.jpg',
  },
  {
    id: 20,
    name: 'Yesido FM Transmitter Y44',
    category: 'chargers',
    price: 3700,
    rating: 4.4,
    reviews: 61,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: 'Bluetooth car FM transmitter with dual USB charging and USB/Micro-SD media playback.',
    tone: ['#FDEA0A', '#2c2c2c'],
    specs: [
      ['Brand', 'Yesido'],
      ['Model', 'Y44'],
      ['Type', 'FM transmitter'],
      ['Connectivity', 'Bluetooth to FM'],
      ['Ports', '2× USB-A charging'],
      ['Media', 'USB drive + Micro SD card'],
    ],
    image: '/products/20.png',
  },
  {
    id: 21,
    name: 'UGREEN MFi Type-C to Lightning Cable',
    category: 'cables',
    price: 4900,
    rating: 4.8,
    reviews: 73,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'MFi-certified braided Type-C to Lightning cable — 3A fast charging, 480Mbps data transfer, 1M.',
    tone: ['#FDEA0A', '#222'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'US304'],
      ['Certification', 'MFi certified (Apple)'],
      ['Length', '1M'],
      ['Current', '3A'],
      ['Data Speed', '480Mbps'],
      ['Build', 'Nylon braided'],
      ['Shell', 'Aluminium'],
    ],
    image: '/products/21.webp',
  },
  {
    id: 22,
    name: 'UGREEN 25W UK Charger + 2M Cable',
    category: 'chargers',
    price: 6200,
    rating: 4.7,
    reviews: 45,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: '25W PD UK wall charger bundled with a 2M Type-C cable — fast charge any USB-C device.',
    tone: ['#FDEA0A', '#2a2a2a'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'CD250'],
      ['Output', '25W PD 3.0'],
      ['Plug', 'UK pin (3-pin)'],
      ['Includes', '2M Type-C to Type-C cable'],
      ['Protocol', 'PD 3.0'],
    ],
    image: '/products/22.webp',
  },
  {
    id: 23,
    name: 'UGREEN 35W GaN Charger UK CD350',
    category: 'chargers',
    price: 7100,
    rating: 4.8,
    reviews: 67,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: '35W dual-port GaN charger with USB-C + USB-A — GaNInfinity™ tech, UK pin.',
    tone: ['#101010', '#FDEA0A'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'CD350'],
      ['Output', '35W total'],
      ['Ports', '1× USB-C + 1× USB-A'],
      ['Tech', 'GaNInfinity™'],
      ['Plug', 'UK pin (3-pin)'],
    ],
    image: '/products/23.webp',
  },
  {
    id: 24,
    name: 'UGREEN 45W GaN Fast Charger UK X524',
    category: 'chargers',
    price: 6700,
    rating: 4.8,
    reviews: 59,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: 'Compact 45W GaN USB-C wall charger with PD 3.0 — fast charges laptops and phones, UK pin.',
    tone: ['#FDEA0A', '#222'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'X524'],
      ['Output', '45W GaN'],
      ['Ports', '1× USB-C'],
      ['Protocol', 'PD 3.0'],
      ['Plug', 'UK pin (3-pin)'],
      ['Design', 'Compact'],
    ],
    image: '/products/24.jpg',
  },
  {
    id: 25,
    name: 'UGREEN 30W Dual Port Car Charger EC305',
    category: 'chargers',
    price: 4050,
    rating: 4.6,
    reviews: 48,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: '30W dual-port car charger — simultaneous USB-C PD + USB-A fast charging.',
    tone: ['#FDEA0A', '#2c2c2c'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'EC305'],
      ['Output', '30W total'],
      ['Ports', '1× USB-C PD + 1× USB-A'],
      ['Charging', 'Simultaneous dual'],
    ],
    image: '/products/25.webp',
  },
  {
    id: 26,
    name: 'UGREEN 60W Dual USB-C Car Charger CD213',
    category: 'chargers',
    price: 5150,
    rating: 4.7,
    reviews: 42,
    stock: 'in',
    warranty: '1 Year Warranty',
    short: '60W dual USB-C car charger — 30W per port, PD 3.0 + QC 3.0, aluminium alloy body.',
    tone: ['#101010', '#FDEA0A'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'CD213'],
      ['Output', '60W total'],
      ['Ports', '2× USB-C PD'],
      ['Per Port', '30W'],
      ['Protocol', 'PD 3.0 · QC 3.0'],
      ['Build', 'Aluminium alloy'],
    ],
    image: '/products/26.webp',
  },
  {
    id: 27,
    name: 'UGREEN USB-A to Type-C Cable US287',
    category: 'cables',
    price: 2050,
    rating: 4.6,
    reviews: 91,
    stock: 'in',
    warranty: '6 Months Warranty',
    short: '18W fast-charge braided USB-A to Type-C cable — 3A, 480Mbps data, 1M nylon braided.',
    tone: ['#FDEA0A', '#2b2b2b'],
    specs: [
      ['Brand', 'UGREEN'],
      ['Model', 'US287'],
      ['Current', '3A (18W)'],
      ['Data Speed', '480Mbps'],
      ['Length', '1M'],
      ['Build', 'Nylon braided'],
    ],
    image: '/products/27.webp',
  },
];
